# Generated by Django 3.1.1 on 2020-11-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='freight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总金额'),
        ),
    ]
